### ISSUE TITLE
Rust style guide

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-backend#13]
We need a Rust style guide, as it is fairly different standards from C++/Java inspired [general style guide](https://github.com/ufosc/resources/blob/master/coding-guidelines/general-style.md). It should be quick to go through (or people won't read it). You can make the PR on the [resources repo](https://github.com/ufosc/resources) and then we will link to it from here.

It would also be great to have [rustfmt](https://github.com/rust-lang-nursery/rustfmt) configured to automatically enforce these polices.

**Comment by igniscyan** [comment]
Started pull request for a baseline on this document. Mentioned a few things in Discord but I'll paste it here for anyone who missed it: 

 I've never used rustfmt before, so I'm looking into making a config for that now. Couple things I'm thinking: 

- 100 character lines
- tabs, not spaces 
- only a maximum of two blank lines between statements (and you'd only do this for ease of reading purposes, ofc)  unless formatting comments
- not sure if it's necessary to enforce the one or the other rule that rust-lang suggests regarding line comments or brick comments. I think allowing both is fine, but up to you guys.

**Comment by mirdaki** [comment]
I've merged your [Rust styling](https://github.com/ufosc/resources/pull/17) pull request into the resources repo. I'll add a reference to it in the CONTRIBUTING file now.

All of those rustfmt settings sound reasonable to me. Be sure to look into having it auto-apply on save or git commit, so we don't have to manually worry about it.

**Comment by mirdaki** [comment]
Closed with #14
